[package]
name = "zbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.*", features = ["derive"] }
env_logger = "0.10.0"
hostname = "0.3.1"
log = "0.4.20"
neofiglet = "0.1.1"
