[package]
name = "zbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.*"
clap = { version = "4.4.*", features = ["derive"] }
env_logger = "0.10.*"
hostname = "0.3.*"
log = "0.4.*"
neofiglet = "0.1.*"
parse_datetime = "0.5.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.107"
zenoh = "0.10.0-rc"

[dependencies.rhai]
version = "1.16.*"
features = [
  "std",
  "serde",
  "decimal",
  "internals",
]
