[package]
name = "zbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.*"
clap = { version = "4.4.*", features = ["derive"] }
easy_reader = "0.5.2"
env_logger = "0.10.*"
hostname = "0.3.*"
log = "0.4.*"
logos = "0.13.0"
neofiglet = "0.1.*"
parse_datetime = "0.5.*"
reqwest = { version="0.11.*", features= ["blocking", "json"] }
rhai-rand = "0.1.6"
rhai-sci = "0.2.0"
rust_search = "2.1.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = { version="1.0.*", default-features = true }
tokio = { version="1.34.*", features = ["full", "time"] }
unit-conversions = "0.1.13"
zenoh = "0.10.0-rc"

[dependencies.rhai]
version = "1.16.*"
features = [
  "std",
  "serde",
  "decimal",
  "internals",
]
